<?php

// Generated by Haxe 3.4.7
class Main {
	public function __construct(){}
	static function main() {
		set_time_limit(120);
		require("../../../vendor/autoload.php");
		$params = php_Web::getParams();
		$data = _hx_explode(",", $params->get("data"));
		$width = Std::parseInt($params->get("width"));
		$height = Std::parseInt($params->get("height"));
		$excel = new PHPExcel();
		Main::create($excel, $data, $width, $height);
		$writer = PHPExcel_IOFactory::createWriter($excel, "Excel2007");
		$writer->save("../output/image.xlsx");
		php_Lib::hprint((new _hx_array(array($data, $width, $height))));
	}
	static function create($excel, $data, $width, $height) {
		$sheet = $excel->getActiveSheet();
		$dataConter = 0;
		{
			$_g1 = 0;
			$_g = $width;
			while($_g1 < $_g) {
				$_g1 = $_g1 + 1;
				$x = $_g1 - 1;
				$sheet->getColumnDimensionByColumn($x)->setWidth(.8);
				{
					$_g3 = 0;
					$_g2 = $height;
					while($_g3 < $_g2) {
						$_g3 = $_g3 + 1;
						$y = $_g3 - 1;
						$color = $data[$dataConter];
						$sheet->getRowDimension($y + 1)->setRowHeight(6);
						$sheet->getStyleByColumnAndRow($x, $y + 1, null, null)->getFill()->setFillType("solid")->getStartColor()->setRGB($color);
						$dataConter = $dataConter + 1;
						unset($y,$color);
					}
					unset($_g3,$_g2);
				}
				unset($x);
			}
		}
	}
	function __toString() { return 'Main'; }
}
